# Generated by Django 2.2.3 on 2019-12-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_id', models.IntegerField()),
                ('index', models.IntegerField()),
                ('guid', models.CharField(max_length=100)),
            ],
        ),
    ]
