# Generated by Django 2.2.3 on 2019-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='has_died',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_id',
            field=models.CharField(max_length=30),
        ),
    ]
